apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
   app: myapp
   version: 2.6.2
spec:
  type: NodePort
  selector:
    app: myapp
    version: 2.6.2
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP